// using glademm V2.6.0
//
// DO NOT EDIT THIS FILE ! It was created using
// glade-- /home/camille/ubuntu/CIES/Atelier_projet/projet_climat_new/climat.glade
// for gtk 2.10.6 and gtkmm 2.10.2
//
// Please modify the corresponding derived classes in ./src/enregister_etat_final_dialog.cc


#if defined __GNUC__ && __GNUC__ < 3
#error This program will crash if compiled with g++ 2.x
// see the dynamic_cast bug in the gtkmm FAQ
#endif //
#include "config.h"
#include <gtkmmconfig.h>
#if GTKMM_MAJOR_VERSION==2 && GTKMM_MINOR_VERSION>2
#include <sigc++/sigc++.h>
#define GMM_GTKMM_22_24(a,b) b
#else //gtkmm 2.2
#define GMM_GTKMM_22_24(a,b) a
#endif //
#include "enregister_etat_final_dialog_glade.hh"
#include <gdk/gdkkeysyms.h>
#include <gtkmm/accelgroup.h>
#include <gtkmm/button.h>
#include <gtkmm/buttonbox.h>
#include <gtkmm/label.h>
#include <gtkmm/box.h>
#include <gtkmm/filechooserwidget.h>
#include "traduction.h"

enregister_etat_final_dialog_glade::enregister_etat_final_dialog_glade(
)
{  
   
   Gtk::Dialog *enregister_etat_final_dialog = this;
   gmm_data = new GlademmData(get_accel_group());
   
   Gtk::Button *cancelbutton8 = Gtk::manage(new class Gtk::Button(Gtk::StockID("gtk-cancel")));
   Gtk::Button *okbutton8 = Gtk::manage(new class Gtk::Button(Gtk::StockID("gtk-ok")));
   Gtk::Label *enregistrer_choix_simulation_label = Gtk::manage(new class Gtk::Label(gettext("Simulation à enregistrer: ")));
   enregistrer_choix_simulation_combobox = Gtk::manage(new class Gtk::ComboBoxText());
   
   Gtk::HBox *enregistrer_choix_simulation_hbox = Gtk::manage(new class Gtk::HBox(false, 0));
   enregistrer_etat_final_filechooserwidget = Gtk::manage(new class Gtk::FileChooserWidget(Gtk::FILE_CHOOSER_ACTION_SAVE,
gettext("Enregistrer Simulation")));
   
   Gtk::VBox *vbox40 = Gtk::manage(new class Gtk::VBox(false, 31));
   cancelbutton8->set_flags(Gtk::CAN_FOCUS);
   cancelbutton8->set_flags(Gtk::CAN_DEFAULT);
   cancelbutton8->set_relief(Gtk::RELIEF_NORMAL);
   okbutton8->set_flags(Gtk::CAN_FOCUS);
   okbutton8->set_flags(Gtk::CAN_DEFAULT);
   okbutton8->set_relief(Gtk::RELIEF_NORMAL);
   enregister_etat_final_dialog->get_action_area()->property_layout_style().set_value(Gtk::BUTTONBOX_END);
   enregistrer_choix_simulation_label->set_alignment(0.5,0.5);
   enregistrer_choix_simulation_label->set_padding(0,0);
   enregistrer_choix_simulation_label->set_justify(Gtk::JUSTIFY_LEFT);
   enregistrer_choix_simulation_label->set_line_wrap(false);
   enregistrer_choix_simulation_label->set_use_markup(false);
   enregistrer_choix_simulation_label->set_selectable(false);
   enregistrer_choix_simulation_combobox->set_size_request(500,-1);
   enregistrer_choix_simulation_hbox->pack_start(*enregistrer_choix_simulation_label, Gtk::PACK_SHRINK, 0);
   enregistrer_choix_simulation_hbox->pack_start(*enregistrer_choix_simulation_combobox);
   vbox40->pack_start(*enregistrer_choix_simulation_hbox);
   vbox40->pack_start(*enregistrer_etat_final_filechooserwidget);
   enregister_etat_final_dialog->get_vbox()->set_homogeneous(false);
   enregister_etat_final_dialog->get_vbox()->set_spacing(0);
   enregister_etat_final_dialog->get_vbox()->pack_start(*vbox40, Gtk::PACK_SHRINK, 0);
   enregister_etat_final_dialog->set_title(gettext("enregistrer l'état final"));
   enregister_etat_final_dialog->set_modal(false);
   enregister_etat_final_dialog->property_window_position().set_value(Gtk::WIN_POS_NONE);
   enregister_etat_final_dialog->set_resizable(true);
   enregister_etat_final_dialog->property_destroy_with_parent().set_value(false);
   enregister_etat_final_dialog->set_has_separator(true);
   enregister_etat_final_dialog->add_action_widget(*cancelbutton8, -6);
   enregister_etat_final_dialog->add_action_widget(*okbutton8, -5);
   cancelbutton8->show();
   okbutton8->show();
   enregistrer_choix_simulation_label->show();
   enregistrer_choix_simulation_combobox->show();
   enregistrer_choix_simulation_hbox->show();
   enregistrer_etat_final_filechooserwidget->show();
   vbox40->show();
   //enregister_etat_final_dialog->show();
   cancelbutton8->signal_clicked().connect(sigc::mem_fun(*this, &enregister_etat_final_dialog_glade::on_cancelbutton8_clicked), true);
   okbutton8->signal_clicked().connect(sigc::mem_fun(*this, &enregister_etat_final_dialog_glade::on_okbutton8_clicked), false);
   enregistrer_choix_simulation_combobox->signal_changed().connect(sigc::mem_fun(*this, &enregister_etat_final_dialog_glade::on_enregistrer_choix_simulation_combobox_changed), true);
}

enregister_etat_final_dialog_glade::~enregister_etat_final_dialog_glade()
{  delete gmm_data;
}
