// using glademm V2.6.0
//
// DO NOT EDIT THIS FILE ! It was created using
// glade-- /home/camille/ubuntu/CIES/Atelier_projet/projet_climat_new/climat.glade
// for gtk 2.10.6 and gtkmm 2.10.2
//
// Please modify the corresponding derived classes in ./src/main_window.hh and./src/main_window.cc

#ifndef _MAIN_WINDOW_GLADE_HH
#  define _MAIN_WINDOW_GLADE_HH


#if !defined(GLADEMM_DATA)
#define GLADEMM_DATA 
#include <gtkmm/accelgroup.h>

class GlademmData
{  
        
        Glib::RefPtr<Gtk::AccelGroup> accgrp;
public:
        
        GlademmData(Glib::RefPtr<Gtk::AccelGroup> ag) : accgrp(ag)
        {  
        }
        
        Glib::RefPtr<Gtk::AccelGroup>  getAccelGroup()
        {  return accgrp;
        }
};
#endif //GLADEMM_DATA

#include <gtkmm/window.h>
#include <gtkmm/label.h>
#include <gtkmm/scale.h>
#include <gtkmm/drawingarea.h>
#include <gtkmm/comboboxtext.h>
#include <gtkmm/statusbar.h>
#include "cairo_graphe.hh"
#include "glext_calottes.hh"
#include "glext_waterlevel.hh"
#include <gtkmm/tooltips.h>


class main_window_glade : public Gtk::Window
{  
        
        GlademmData *gmm_data;
public:
        class Gtk::Label * legende_texte_label;
        class Gtk::HScale * time_slider_hscale;
        class glext_calottes * calotte_drawingarea;
        class glext_waterlevel * niveau_mer_drawingarea;
        class Gtk::ComboBoxText * graphe_two_combobox;
        class cairo_graphe * graphe_two_drawingarea;
        class Gtk::ComboBoxText * graphe_three_combobox;
        class cairo_graphe * graphe_three_drawingarea;
        class Gtk::ComboBoxText * graphe_four_combobox;
        class cairo_graphe * graphe_four_drawingarea;
        class Gtk::ComboBoxText * graphe_one_combobox;
        class cairo_graphe * graphe_one_drawingarea;
        class Gtk::Statusbar * main_window_statusbar;
	class Gtk::CheckMenuItem *animations_menuitem;
protected:        
        main_window_glade();
        
        ~main_window_glade();

	Gtk::Tooltips m_tooltips;
private:
        virtual void on_new1_activate() = 0;
        virtual void on_superposer_menuitem_activate() = 0;
        virtual void on_save1_activate() = 0;
        virtual void on_quit1_activate() = 0;
        virtual void on_animations_menuitem_activate() = 0;
        virtual void on_about1_activate() = 0;
        virtual void on_nouvelle_simulation_button_clicked() = 0;
        virtual void on_superposer_button_clicked() = 0;
        virtual void on_enregistrer_etat_final_button_clicked() = 0;
        virtual void on_time_slider_hscale_value_changed() = 0;
        virtual void on_graphe_two_combobox_changed() = 0;
        virtual void on_graphe_three_combobox_changed() = 0;
        virtual void on_graphe_four_combobox_changed() = 0;
        virtual void on_graphe_one_combobox_changed() = 0;
};
#endif
